# Randomization challenge for the 9-gene TTLL/AGBL panel across three external datasets
#
# This script:
# 1. reads matched TCGA tumour-normal DESeq2 objects
# 2. extracts VST-transformed expression values and maps genes to symbols
# 3. builds three external validation datasets:
#    - GSE87410 lung cohort
#    - CPTAC kidney cohort
#    - Korean CRC cohort
# 4. trains a pancancer random forest model on the observed 9-gene panel
# 5. computes its mean AUC across the three external datasets
# 6. compares it with 100 random 9-gene panels sampled from the shared gene universe
# 7. compares it with size-matched 9-gene panels sampled from cancer-relevant
#    MSigDB Hallmark gene sets
# 8. reports empirical p-values and plots the null distributions
#
# Input:
# - dds_*_matched_group.rds files
# - GSE87410_raw_counts_GRCh38.p13_NCBI.tsv.gz
# - GSM_sample_map.csv
# - downloaded CPTAC kidney STAR-count files in GDC_kidney_filtered/
# - CMCBSN_expectedcount_342.txt
#
#
# Notes:
# - Edit all input paths below before running
# - The observed panel is the fixed 9-gene model:
#   TTLL4, TTLL5, TTLL6, TTLL7, TTLL11, AGBL1, AGBL3, AGBL4, AGBL5
# - Random panels are sampled from the shared gene universe present in TCGA
#   and in all three external datasets
# - Hallmark-derived panels are generated by sampling 10 random 9-gene subsets
#   from each selected cancer-relevant Hallmark pathway
# - The transcriptome-wide null distribution uses 100 random panels by default

suppressPackageStartupMessages({
  library(DESeq2)
  library(tidyverse)
  library(biomaRt)
  library(AnnotationDbi)
  library(org.Hs.eg.db)
  library(caret)
  library(randomForest)
  library(pROC)
  library(ggplot2)
  library(TCGAbiolinks)
  library(msigdbr)
})

set.seed(42)

# ------------------------------------------------------------------
# Input paths
# ------------------------------------------------------------------

tcga_dir <- "path-to-tcga-dds-files"

lung_dir <- "path-to-GSE87410-folder"

kidney_dir <- "path-to-CPTAC-kidney-folder"
kidney_counts_dir <- file.path(kidney_dir, "GDC_kidney_filtered")

crc_dir <- "path-to-korean-crc-folder"

lung_counts_file <- file.path(lung_dir, "GSE87410_raw_counts_GRCh38.p13_NCBI.tsv.gz")
lung_map_file <- file.path(lung_dir, "GSM_sample_map.csv")
crc_counts_file <- file.path(crc_dir, "CMCBSN_expectedcount_342.txt")

if (!dir.exists(tcga_dir)) {
  stop("Please set 'tcga_dir' to the folder containing dds_*_matched_group.rds files.")
}

if (!dir.exists(lung_dir)) {
  stop("Please set 'lung_dir' to the folder containing the GSE87410 files.")
}
if (!file.exists(lung_counts_file)) {
  stop("Could not find: ", lung_counts_file)
}
if (!file.exists(lung_map_file)) {
  stop("Could not find: ", lung_map_file)
}
if (!dir.exists(kidney_counts_dir)) {
  stop("Please set 'kidney_dir' so that GDC_kidney_filtered/ exists inside it.")
}
if (!dir.exists(crc_dir)) {
  stop("Please set 'crc_dir' to the folder containing the Korean CRC counts.")
}
if (!file.exists(crc_counts_file)) {
  stop("Could not find: ", crc_counts_file)
}

# ------------------------------------------------------------------
# Observed 9-gene panel
# ------------------------------------------------------------------

feature_genes <- c(
  "TTLL4", "TTLL5", "TTLL6", "TTLL7", "TTLL11",
  "AGBL1", "AGBL3", "AGBL4", "AGBL5"
)

# ------------------------------------------------------------------
# Gene symbol mapping for TCGA
# ------------------------------------------------------------------

message("Fetching Ensembl to gene symbol mapping via biomaRt...")
ensembl <- useMart("ensembl", dataset = "hsapiens_gene_ensembl")

gene_map <- getBM(
  attributes = c("ensembl_gene_id", "external_gene_name"),
  mart = ensembl
) %>%
  filter(external_gene_name != "") %>%
  distinct(ensembl_gene_id, .keep_all = TRUE)

# ------------------------------------------------------------------
# Load and VST-normalize TCGA matched cohorts
# ------------------------------------------------------------------

message("Loading TCGA matched DESeq2 objects...")
dds_files <- list.files(
  tcga_dir,
  pattern = "dds_.*_matched_group\\.rds$",
  full.names = TRUE
)

if (length(dds_files) == 0) {
  stop("No TCGA DESeq2 files found in 'tcga_dir'.")
}

tcga_list <- list()

for (f in dds_files) {
  proj <- sub("dds_(.*)_matched_group\\.rds", "\\1", basename(f))
  dds <- readRDS(f)
  vsd <- vst(dds, blind = TRUE)
  mat <- assay(vsd)

  ens <- sub("\\..*", "", rownames(mat))
  syms <- gene_map$external_gene_name[match(ens, gene_map$ensembl_gene_id)]

  keep <- !is.na(syms) & syms != ""
  mat <- mat[keep, , drop = FALSE]
  rownames(mat) <- syms[keep]

  expr <- as.data.frame(t(mat))
  expr$sample <- rownames(expr)
  expr$condition <- as.character(colData(dds)[expr$sample, "condition"])
  expr$project <- proj

  tcga_list[[proj]] <- expr
}

tcga_df <- bind_rows(tcga_list) %>%
  filter(!is.na(condition)) %>%
  relocate(sample, condition, project)

tcga_labels <- factor(
  ifelse(tcga_df$condition == "Primary Tumor", "Tumor", "Normal"),
  levels = c("Normal", "Tumor")
)

gene_universe_tcga <- setdiff(colnames(tcga_df), c("sample", "condition", "project"))

# ------------------------------------------------------------------
# Fixed cross-validation settings
# ------------------------------------------------------------------

ctrl_pan <- trainControl(
  method = "cv",
  number = 5,
  classProbs = TRUE,
  summaryFunction = twoClassSummary,
  savePredictions = TRUE
)

tune_len <- 5


# ------------------------------------------------------------------
# External dataset 1: Lung GSE87410
# ------------------------------------------------------------------

message("Loading GSE87410 lung cohort...")

raw_counts_lung <- readr::read_tsv(lung_counts_file, show_col_types = FALSE)
counts_lung <- as.data.frame(raw_counts_lung[, -1])
rownames(counts_lung) <- raw_counts_lung[[1]]
counts_lung[] <- lapply(counts_lung, as.numeric)

gsm_map <- readr::read_csv(
  lung_map_file,
  col_names = c("GSM", "Label"),
  show_col_types = FALSE
) %>%
  tidyr::separate(Label, into = c("Project", "Patient", "Tissue"), sep = "_") %>%
  filter(Tissue %in% c("T", "N"))

common_lung <- intersect(gsm_map$GSM, colnames(counts_lung))
counts_lung <- counts_lung[, common_lung, drop = FALSE]
meta_lung <- gsm_map %>%
  filter(GSM %in% common_lung) %>%
  column_to_rownames("GSM")

dds_l <- DESeqDataSetFromMatrix(
  countData = counts_lung,
  colData = meta_lung,
  design = ~ Tissue
)

vsd_l <- vst(dds_l, blind = TRUE)
mat_l <- assay(vsd_l)

sym_l <- mapIds(
  org.Hs.eg.db,
  keys = rownames(mat_l),
  column = "SYMBOL",
  keytype = "ENTREZID",
  multiVals = "first"
)

rownames(mat_l) <- ifelse(is.na(sym_l) | sym_l == "", rownames(mat_l), sym_l)

lung_expr_full <- as.data.frame(t(mat_l))
lung_truth <- factor(
  ifelse(meta_lung$Tissue == "T", "Tumor", "Normal"),
  levels = c("Normal", "Tumor")
)

# ------------------------------------------------------------------
# External dataset 2: Kidney CPTAC-3
# ------------------------------------------------------------------

message("Loading CPTAC kidney cohort...")

count_files_kidney <- list.files(
  kidney_counts_dir,
  pattern = "\\.tsv$",
  recursive = TRUE,
  full.names = TRUE
)

expr_list_kidney <- list()

for (f in count_files_kidney) {
  dat <- readr::read_tsv(f, skip = 1, show_col_types = FALSE) %>%
    dplyr::select(gene_id, gene_name, count = unstranded) %>%
    mutate(
      gene_id = sub("\\..*", "", gene_id),
      count = as.numeric(count)
    ) %>%
    filter(!is.na(gene_name)) %>%
    group_by(gene_name) %>%
    summarise(count = sum(count), .groups = "drop")

  sid <- basename(dirname(f))
  expr_list_kidney[[sid]] <- dat %>%
    rename(!!sid := count)
}

expr_merged_kidney <- Reduce(function(a, b) full_join(a, b, by = "gene_name"), expr_list_kidney) %>%
  column_to_rownames("gene_name")

clinical_data <- GDCquery_clinic(project = "CPTAC-3", type = "clinical")

query_expr <- GDCquery(
  project = "CPTAC-3",
  data.category = "Transcriptome Profiling",
  data.type = "Gene Expression Quantification",
  workflow.type = "STAR - Counts"
)

metadata_expr <- getResults(
  query_expr,
  cols = c("file_id", "cases.submitter_id", "sample_type")
)

metadata_kid <- metadata_expr %>%
  filter(
    file_id %in% colnames(expr_merged_kidney),
    sample_type %in% c("Primary Tumor", "Solid Tissue Normal")
  ) %>%
  dplyr::select(sample = file_id, condition = sample_type) %>%
  mutate(
    condition = factor(
      ifelse(grepl("Normal", condition), "Normal", "Tumor"),
      levels = c("Normal", "Tumor")
    )
  ) %>%
  distinct() %>%
  column_to_rownames("sample")

dds_k <- DESeqDataSetFromMatrix(
  expr_merged_kidney[, rownames(metadata_kid), drop = FALSE],
  metadata_kid,
  design = ~ condition
)

vsd_k <- vst(dds_k, blind = TRUE)
mat_k <- assay(vsd_k)

kidney_expr_full <- as.data.frame(t(mat_k))
kidney_truth <- metadata_kid$condition

# ------------------------------------------------------------------
# External dataset 3: Korean CRC
# ------------------------------------------------------------------

message("Loading Korean CRC cohort...")

raw_tab_crc <- read.delim(crc_counts_file, check.names = FALSE)
gene_symbols_crc <- raw_tab_crc[[1]]
counts_crc <- as.data.frame(raw_tab_crc[, -1, drop = FALSE])
rownames(counts_crc) <- gene_symbols_crc
counts_crc[] <- lapply(counts_crc, function(x) as.numeric(as.character(x)))

counts_sym_crc <- as.data.frame(
  rowsum(
    as.matrix(counts_crc),
    group = rownames(counts_crc),
    reorder = FALSE,
    na.rm = TRUE
  )
)

sids_crc <- colnames(counts_sym_crc)
tissue_crc <- ifelse(grepl("-T-", sids_crc), "T", ifelse(grepl("-N-", sids_crc), "N", NA))

sample_info_crc <- data.frame(
  GSM = sids_crc,
  Tissue = tissue_crc,
  row.names = sids_crc,
  stringsAsFactors = FALSE
) %>%
  dplyr::filter(!is.na(Tissue))

counts_sym_crc <- counts_sym_crc[, rownames(sample_info_crc), drop = FALSE]

dds_crc <- DESeq2::DESeqDataSetFromMatrix(
  countData = round(counts_sym_crc),
  colData = sample_info_crc,
  design = ~ Tissue
)

vsd_crc <- DESeq2::vst(dds_crc, blind = TRUE)
mat_crc <- SummarizedExperiment::assay(vsd_crc)

crc_expr_full <- as.data.frame(t(mat_crc))
crc_truth <- factor(
  ifelse(sample_info_crc$Tissue == "T", "Tumor", "Normal"),
  levels = c("Normal", "Tumor")
)

# ------------------------------------------------------------------
# Assemble external sets
# ------------------------------------------------------------------

ext_sets <- list(
  Lung = list(expr = lung_expr_full, truth = lung_truth),
  Kidney = list(expr = kidney_expr_full, truth = kidney_truth),
  CRC_KR = list(expr = crc_expr_full, truth = crc_truth)
)

# ------------------------------------------------------------------
# Build shared gene universe
# ------------------------------------------------------------------

common_ext <- Reduce(intersect, lapply(ext_sets, function(s) colnames(s$expr)))
gene_universe <- intersect(gene_universe_tcga, common_ext)

na_free <- gene_universe[
  colSums(is.na(tcga_df[, gene_universe, drop = FALSE])) == 0
]

gene_universe <- na_free

if (length(gene_universe) < 9) {
  stop("Shared gene universe contains fewer than 9 genes.")
}

missing_in_ext <- setdiff(feature_genes, gene_universe)
if (length(missing_in_ext) > 0) {
  warning(
    "Some panel genes are missing across datasets: ",
    paste(missing_in_ext, collapse = ", "),
    "\nThey will be dropped from evaluation."
  )
}

panel_eval_genes <- intersect(feature_genes, gene_universe)

if (length(panel_eval_genes) < 5) {
  stop("Fewer than 5 observed panel genes remain after intersection across datasets.")
}

# ------------------------------------------------------------------
# Helper: fit and evaluate one gene set
# ------------------------------------------------------------------

eval_gene_set <- function(genes, verbose = FALSE) {
  x_tr <- tcga_df[, genes, drop = FALSE]
  y_tr <- factor(
    ifelse(tcga_df$condition == "Primary Tumor", "Tumor", "Normal"),
    levels = c("Normal", "Tumor")
  )

  rf_mod <- train(
    x = x_tr,
    y = y_tr,
    method = "rf",
    metric = "ROC",
    trControl = ctrl_pan,
    tuneLength = tune_len
  )

  aucs <- purrr::map_dbl(names(ext_sets), function(nm) {
    s <- ext_sets[[nm]]
    X <- s$expr[, genes, drop = FALSE]
    X[] <- lapply(X, as.numeric)

    probs <- predict(rf_mod, newdata = X, type = "prob")[, "Tumor"]
    roc_obj <- pROC::roc(s$truth, probs, quiet = TRUE)
    a <- as.numeric(pROC::auc(roc_obj))

    if (verbose) {
      message("  ", nm, " AUC = ", sprintf("%.3f", a))
    }

    a
  })

  mean(aucs)
}

# ------------------------------------------------------------------
# Observed panel
# ------------------------------------------------------------------

message("Evaluating observed panel: ", paste(panel_eval_genes, collapse = ", "))
set.seed(31)
obs_auc <- eval_gene_set(panel_eval_genes, verbose = TRUE)

message("Observed mean AUC across 3 external datasets = ", sprintf("%.3f", obs_auc))

# ------------------------------------------------------------------
# Null distribution: 100 random 9-gene panels
# ------------------------------------------------------------------

n_rand <- 100
message("Sampling ", n_rand, " random 9-gene panels from shared gene universe (n = ", length(gene_universe), ")...")

null_res <- tibble(
  genes = replicate(n_rand, sample(gene_universe, 9), simplify = FALSE)
) %>%
  mutate(auc = purrr::map_dbl(genes, eval_gene_set))

p_emp <- mean(null_res$auc >= obs_auc)
n_better <- sum(null_res$auc >= obs_auc)

cat("\n------------------------------------------------------------\n")
cat("Observed mean AUC (true 9-gene panel): ", sprintf("%.3f", obs_auc), "\n", sep = "")
cat("Random panels with AUC >= observed:    ", n_better, " / ", n_rand,
    "  (empirical p = ", sprintf("%.3f", p_emp), ")\n", sep = "")
cat("------------------------------------------------------------\n\n")

top_random <- null_res %>%
  mutate(panel = purrr::map_chr(genes, ~ paste(.x, collapse = ", "))) %>%
  arrange(desc(auc))

print(head(top_random, 10), n = 10)

# ------------------------------------------------------------------
# Plot null distribution
# ------------------------------------------------------------------

hist(
  null_res$auc,
  breaks = 20,
  col = "lightgray",
  border = "white",
  xlim = c(0, 1),
  xaxt = "n",
  main = "Null distribution of mean AUC from random 9-gene panels",
  xlab = "Mean AUC across Lung, Kidney, and Korean CRC"
)

axis(1, at = seq(0, 1, by = 0.1), labels = sprintf("%.1f", seq(0, 1, by = 0.1)))
abline(v = obs_auc, col = "red", lwd = 2)
mtext(sprintf("Observed = %.3f | p = %.3f", obs_auc, p_emp), side = 3)



n_per_hallmark <- 10
set.seed(777)

# ------------------------------------------------------------------
# Load MSigDB Hallmark gene sets
# ------------------------------------------------------------------

message("Loading MSigDB Hallmark gene sets...")

hallmark_sets <- msigdbr(
  species = "Homo sapiens",
  collection = "H"
) %>%
  dplyr::select(gs_name, gene_symbol) %>%
  dplyr::filter(gene_symbol %in% gene_universe)

# ------------------------------------------------------------------
# Select cancer-relevant Hallmark pathways
# ------------------------------------------------------------------

cancer_hallmarks <- c(
  "HALLMARK_EPITHELIAL_MESENCHYMAL_TRANSITION",
  "HALLMARK_ANGIOGENESIS",
  "HALLMARK_HYPOXIA",
  "HALLMARK_GLYCOLYSIS",
  "HALLMARK_MYC_TARGETS_V1",
  "HALLMARK_MYC_TARGETS_V2",
  "HALLMARK_E2F_TARGETS",
  "HALLMARK_G2M_CHECKPOINT",
  "HALLMARK_P53_PATHWAY",
  "HALLMARK_APOPTOSIS",
  "HALLMARK_TNFA_SIGNALING_VIA_NFKB",
  "HALLMARK_IL6_JAK_STAT3_SIGNALING",
  "HALLMARK_PI3K_AKT_MTOR_SIGNALING",
  "HALLMARK_MTORC1_SIGNALING",
  "HALLMARK_KRAS_SIGNALING_UP",
  "HALLMARK_WNT_BETA_CATENIN_SIGNALING",
  "HALLMARK_TGF_BETA_SIGNALING",
  "HALLMARK_INFLAMMATORY_RESPONSE"
)

established_sets <- hallmark_sets %>%
  dplyr::filter(gs_name %in% cancer_hallmarks) %>%
  dplyr::group_by(gs_name) %>%
  dplyr::summarise(
    genes = list(unique(gene_symbol)),
    n_genes = length(unique(gene_symbol)),
    .groups = "drop"
  ) %>%
  dplyr::filter(n_genes >= 9)

if (nrow(established_sets) == 0) {
  stop("No Hallmark gene sets with at least 9 genes were found in the shared gene universe.")
}

message("Number of Hallmark pathways retained: ", nrow(established_sets))

# ------------------------------------------------------------------
# Sample 10 random 9-gene panels from each Hallmark pathway
# ------------------------------------------------------------------

message(
  "Sampling ",
  n_per_hallmark,
  " random 9-gene panels from each Hallmark pathway..."
)

hallmark_9_iter <- established_sets %>%
  dplyr::select(gs_name, genes) %>%
  tidyr::uncount(weights = n_per_hallmark, .id = "iter") %>%
  dplyr::rowwise() %>%
  dplyr::mutate(
    genes_9 = list(sample(genes, 9))
  ) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(
    auc = NA_real_
  )

# ------------------------------------------------------------------
# Evaluate each Hallmark-derived 9-gene panel
# ------------------------------------------------------------------

for (i in seq_len(nrow(hallmark_9_iter))) {
  message(
    "Running Hallmark 9-gene panel ",
    i, " / ", nrow(hallmark_9_iter),
    " | ", hallmark_9_iter$gs_name[i],
    " | iteration ", hallmark_9_iter$iter[i],
    " at ", Sys.time()
  )

  hallmark_9_iter$auc[i] <- eval_gene_set(
    hallmark_9_iter$genes_9[[i]]
  )

  saveRDS(hallmark_9_iter, "hallmark_9_iter_checkpoint.rds")
}

saveRDS(hallmark_9_iter, "hallmark_9_iter_final.rds")

# ------------------------------------------------------------------
# Summarize Hallmark-derived panel performance
# ------------------------------------------------------------------

hallmark_9_summary <- hallmark_9_iter %>%
  dplyr::group_by(gs_name) %>%
  dplyr::summarise(
    n_iter = dplyr::n(),
    mean_auc = mean(auc, na.rm = TRUE),
    median_auc = median(auc, na.rm = TRUE),
    min_auc = min(auc, na.rm = TRUE),
    max_auc = max(auc, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  dplyr::arrange(desc(mean_auc))

print(hallmark_9_summary, n = Inf)

# ------------------------------------------------------------------
# Empirical p-value
# ------------------------------------------------------------------

p_emp_hallmark_9 <- mean(hallmark_9_iter$auc >= obs_auc, na.rm = TRUE)
n_better_hallmark_9 <- sum(hallmark_9_iter$auc >= obs_auc, na.rm = TRUE)
n_total_hallmark_9 <- sum(!is.na(hallmark_9_iter$auc))

cat("\n------------------------------------------------------------\n")
cat("Observed mean AUC (TTLL/AGBL 9-gene panel): ", sprintf("%.3f", obs_auc), "\n", sep = "")
cat("Hallmark-derived 9-gene panels with AUC >= observed: ",
    n_better_hallmark_9, " / ", n_total_hallmark_9,
    "  (empirical p = ", sprintf("%.3f", p_emp_hallmark_9), ")\n", sep = "")
cat("------------------------------------------------------------\n\n")

# ------------------------------------------------------------------
# Plot null distribution
# ------------------------------------------------------------------

hist(
  hallmark_9_iter$auc,
  breaks = 20,
  col = "lightgray",
  border = "white",
  xlim = c(0, 1),
  xaxt = "n",
  main = "Null distribution of mean AUC from Hallmark-derived 9-gene panels",
  xlab = "Mean AUC across Lung, Kidney, and Korean CRC"
)

axis(
  1,
  at = seq(0, 1, by = 0.1),
  labels = sprintf("%.1f", seq(0, 1, by = 0.1))
)

abline(v = obs_auc, col = "red", lwd = 2)

mtext(
  sprintf("Observed = %.3f | p = %.3f", obs_auc, p_emp_hallmark_9),
  side = 3
)

message("Hallmark 9-gene randomization challenge complete.")
